from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import sys


#界面仅对日历默认时间进行了修改


class Ui_userset(object):
    def setupUi(self, userset):
        userset.setObjectName("userset")
        userset.resize(720, 566)
        self.gridLayout = QtWidgets.QGridLayout(userset)
        self.gridLayout.setObjectName("gridLayout")
        self.setting = QtWidgets.QTabWidget(userset)
        self.setting.setEnabled(True)
        self.setting.setMinimumSize(QtCore.QSize(80, 30))
        self.setting.setMouseTracking(False)
        self.setting.setStyleSheet("QWidget::tab{height:40px;width:120px;}")
        self.setting.setIconSize(QtCore.QSize(16, 16))
        self.setting.setObjectName("setting")
        self.insert = QtWidgets.QWidget()
        self.insert.setEnabled(True)
        self.insert.setWhatsThis("")
        self.insert.setObjectName("insert")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.insert)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.insert)
        self.label_8.setMinimumSize(QtCore.QSize(340, 100))
        self.label_8.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:25px \"方正小标宋简体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.insert)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.inputin = QtWidgets.QRadioButton(self.groupBox_3)
        self.inputin.setGeometry(QtCore.QRect(50, 5, 109, 18))
        self.inputin.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.inputin.setChecked(True)
        self.inputin.setObjectName("inputin")
        self.inputout = QtWidgets.QRadioButton(self.groupBox_3)
        self.inputout.setGeometry(QtCore.QRect(170, 5, 160, 18))
        self.inputout.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.inputout.setObjectName("inputout")
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.num1 = QtWidgets.QLabel(self.insert)
        self.num1.setMinimumSize(QtCore.QSize(40, 25))
        self.num1.setMaximumSize(QtCore.QSize(40, 25))
        self.num1.setObjectName("num1")
        self.horizontalLayout_2.addWidget(self.num1)
        self.num = QtWidgets.QLineEdit(self.insert)
        self.num.setMinimumSize(QtCore.QSize(200, 25))
        self.num.setMaximumSize(QtCore.QSize(200, 25))
        self.num.setObjectName("num")
        self.horizontalLayout_2.addWidget(self.num)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.name1 = QtWidgets.QLabel(self.insert)
        self.name1.setMinimumSize(QtCore.QSize(40, 25))
        self.name1.setMaximumSize(QtCore.QSize(40, 25))
        self.name1.setObjectName("name1")
        self.horizontalLayout_3.addWidget(self.name1)
        self.name = QtWidgets.QLineEdit(self.insert)
        self.name.setMinimumSize(QtCore.QSize(200, 25))
        self.name.setMaximumSize(QtCore.QSize(200, 25))
        self.name.setObjectName("name")
        self.horizontalLayout_3.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sex1 = QtWidgets.QLabel(self.insert)
        self.sex1.setMinimumSize(QtCore.QSize(40, 25))
        self.sex1.setMaximumSize(QtCore.QSize(40, 25))
        self.sex1.setObjectName("sex1")
        self.horizontalLayout_4.addWidget(self.sex1)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.groupBox_2 = QtWidgets.QGroupBox(self.insert)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 25))
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 25))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.sex_man = QtWidgets.QRadioButton(self.groupBox_2)
        self.sex_man.setGeometry(QtCore.QRect(32, 4, 100, 18))
        self.sex_man.setMinimumSize(QtCore.QSize(100, 0))
        self.sex_man.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sex_man.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.sex_man.setChecked(True)
        self.sex_man.setObjectName("sex_man")
        self.sex_wo = QtWidgets.QRadioButton(self.groupBox_2)
        self.sex_wo.setGeometry(QtCore.QRect(122, 4, 100, 18))
        self.sex_wo.setMinimumSize(QtCore.QSize(100, 0))
        self.sex_wo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sex_wo.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.sex_wo.setObjectName("sex_wo")
        self.horizontalLayout_32.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_32)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.other1 = QtWidgets.QLabel(self.insert)
        self.other1.setMinimumSize(QtCore.QSize(40, 25))
        self.other1.setMaximumSize(QtCore.QSize(40, 25))
        self.other1.setObjectName("other1")
        self.horizontalLayout_5.addWidget(self.other1)
        self.other = QtWidgets.QLineEdit(self.insert)
        self.other.setMinimumSize(QtCore.QSize(200, 25))
        self.other.setMaximumSize(QtCore.QSize(200, 25))
        self.other.setObjectName("other")
        self.horizontalLayout_5.addWidget(self.other)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cancel = QtWidgets.QPushButton(self.insert)
        self.cancel.setMinimumSize(QtCore.QSize(80, 25))
        self.cancel.setMaximumSize(QtCore.QSize(80, 25))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_6.addWidget(self.cancel)
        self.commit = QtWidgets.QPushButton(self.insert)
        self.commit.setMinimumSize(QtCore.QSize(80, 25))
        self.commit.setMaximumSize(QtCore.QSize(80, 25))
        self.commit.setObjectName("commit")
        self.horizontalLayout_6.addWidget(self.commit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.insert)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.insert)
        self.label.setMinimumSize(QtCore.QSize(330, 400))
        self.label.setStyleSheet("background-color:rgba(0,0,0,91);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.start = QtWidgets.QPushButton(self.insert)
        self.start.setMinimumSize(QtCore.QSize(80, 25))
        self.start.setMaximumSize(QtCore.QSize(80, 25))
        self.start.setObjectName("start")
        self.horizontalLayout_7.addWidget(self.start)
        self.start_2 = QtWidgets.QPushButton(self.insert)
        self.start_2.setMinimumSize(QtCore.QSize(80, 25))
        self.start_2.setMaximumSize(QtCore.QSize(80, 25))
        self.start_2.setObjectName("start_2")
        self.horizontalLayout_7.addWidget(self.start_2)
        self.start_3 = QtWidgets.QPushButton(self.insert)
        self.start_3.setMinimumSize(QtCore.QSize(80, 25))
        self.start_3.setMaximumSize(QtCore.QSize(80, 25))
        self.start_3.setObjectName("start_3")
        self.horizontalLayout_7.addWidget(self.start_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.label_2 = QtWidgets.QLabel(self.insert)
        self.label_2.setMinimumSize(QtCore.QSize(300, 25))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.setting.addTab(self.insert, "")
        self.update = QtWidgets.QWidget()
        self.update.setObjectName("update")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.update)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.update)
        self.label_10.setMinimumSize(QtCore.QSize(250, 100))
        self.label_10.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:25px \"方正小标宋简体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.groupBox_4 = QtWidgets.QGroupBox(self.update)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.editin = QtWidgets.QRadioButton(self.groupBox_4)
        self.editin.setGeometry(QtCore.QRect(50, 6, 109, 18))
        self.editin.setMinimumSize(QtCore.QSize(0, 0))
        self.editin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.editin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.editin.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.editin.setChecked(True)
        self.editin.setAutoExclusive(True)
        self.editin.setObjectName("editin")
        self.editout = QtWidgets.QRadioButton(self.groupBox_4)
        self.editout.setGeometry(QtCore.QRect(170, 6, 158, 18))
        self.editout.setMinimumSize(QtCore.QSize(0, 0))
        self.editout.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.editout.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.editout.setObjectName("editout")
        self.horizontalLayout_65.addWidget(self.groupBox_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_65)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.num1_2 = QtWidgets.QLabel(self.update)
        self.num1_2.setMinimumSize(QtCore.QSize(40, 25))
        self.num1_2.setMaximumSize(QtCore.QSize(40, 25))
        self.num1_2.setObjectName("num1_2")
        self.horizontalLayout_10.addWidget(self.num1_2)
        self.num_2 = QtWidgets.QLineEdit(self.update)
        self.num_2.setMinimumSize(QtCore.QSize(200, 25))
        self.num_2.setMaximumSize(QtCore.QSize(200, 25))
        self.num_2.setObjectName("num_2")
        self.horizontalLayout_10.addWidget(self.num_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.name1_2 = QtWidgets.QLabel(self.update)
        self.name1_2.setMinimumSize(QtCore.QSize(40, 25))
        self.name1_2.setMaximumSize(QtCore.QSize(40, 25))
        self.name1_2.setObjectName("name1_2")
        self.horizontalLayout_11.addWidget(self.name1_2)
        self.name_2 = QtWidgets.QLineEdit(self.update)
        self.name_2.setMinimumSize(QtCore.QSize(200, 25))
        self.name_2.setMaximumSize(QtCore.QSize(200, 25))
        self.name_2.setObjectName("name_2")
        self.horizontalLayout_11.addWidget(self.name_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sex1_2 = QtWidgets.QLabel(self.update)
        self.sex1_2.setMinimumSize(QtCore.QSize(40, 25))
        self.sex1_2.setMaximumSize(QtCore.QSize(40, 25))
        self.sex1_2.setMouseTracking(True)
        self.sex1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sex1_2.setLineWidth(1)
        self.sex1_2.setObjectName("sex1_2")
        self.horizontalLayout_12.addWidget(self.sex1_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.update)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 25))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 25))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.sex_man_2 = QtWidgets.QRadioButton(self.groupBox)
        self.sex_man_2.setGeometry(QtCore.QRect(31, 2, 100, 18))
        self.sex_man_2.setMinimumSize(QtCore.QSize(100, 0))
        self.sex_man_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sex_man_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sex_man_2.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.sex_man_2.setChecked(True)
        self.sex_man_2.setAutoExclusive(True)
        self.sex_man_2.setObjectName("sex_man_2")
        self.sex_wo_2 = QtWidgets.QRadioButton(self.groupBox)
        self.sex_wo_2.setGeometry(QtCore.QRect(120, 2, 100, 18))
        self.sex_wo_2.setMinimumSize(QtCore.QSize(100, 0))
        self.sex_wo_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sex_wo_2.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.sex_wo_2.setObjectName("sex_wo_2")
        self.horizontalLayout_9.addWidget(self.groupBox)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.other1_2 = QtWidgets.QLabel(self.update)
        self.other1_2.setMinimumSize(QtCore.QSize(40, 25))
        self.other1_2.setMaximumSize(QtCore.QSize(40, 25))
        self.other1_2.setObjectName("other1_2")
        self.horizontalLayout_13.addWidget(self.other1_2)
        self.other_2 = QtWidgets.QLineEdit(self.update)
        self.other_2.setMinimumSize(QtCore.QSize(200, 25))
        self.other_2.setMaximumSize(QtCore.QSize(200, 25))
        self.other_2.setObjectName("other_2")
        self.horizontalLayout_13.addWidget(self.other_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.search = QtWidgets.QPushButton(self.update)
        self.search.setMinimumSize(QtCore.QSize(80, 25))
        self.search.setMaximumSize(QtCore.QSize(80, 25))
        self.search.setObjectName("search")
        self.horizontalLayout_14.addWidget(self.search)
        self.edit = QtWidgets.QPushButton(self.update)
        self.edit.setMinimumSize(QtCore.QSize(80, 25))
        self.edit.setMaximumSize(QtCore.QSize(80, 25))
        self.edit.setObjectName("edit")
        self.horizontalLayout_14.addWidget(self.edit)
        self.delpeo = QtWidgets.QPushButton(self.update)
        self.delpeo.setMinimumSize(QtCore.QSize(80, 25))
        self.delpeo.setMaximumSize(QtCore.QSize(80, 25))
        self.delpeo.setObjectName("delpeo")
        self.horizontalLayout_14.addWidget(self.delpeo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.xiu = QtWidgets.QLabel(self.update)
        self.xiu.setObjectName("xiu")
        self.verticalLayout_4.addWidget(self.xiu)
        self.xiu_2 = QtWidgets.QLabel(self.update)
        self.xiu_2.setObjectName("xiu_2")
        self.verticalLayout_4.addWidget(self.xiu_2)
        self.label_3 = QtWidgets.QLabel(self.update)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        spacerItem11 = QtWidgets.QSpacerItem(321, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.update)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_15.addWidget(self.line_2)
        self.tableWidget = QtWidgets.QTableWidget(self.update)
        self.tableWidget.setMinimumSize(QtCore.QSize(340, 400))
        self.tableWidget.setStyleSheet("QTableWidget{background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,0);color: rgba(0, 0, 0,255);border-style:none;border-width:1px;border-radius:0px;alternate-background-color:rgba(0,0,0,36);gridline-color:rgba(0,6,3,0);font:19px \"宋体\";}QHeaderView::section{border-style:none;border-width:1px;border-radius:0px;background-color:rgba(0,0,0,42);border-color:rgba(0,0,0,136);}")
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.horizontalLayout_15.addWidget(self.tableWidget)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.setting.addTab(self.update, "")
        self.leave = QtWidgets.QWidget()
        self.leave.setObjectName("leave")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.leave)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.leave)
        self.label_11.setMinimumSize(QtCore.QSize(340, 100))
        self.label_11.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:25px \"方正小标宋简体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem12)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.num1_3 = QtWidgets.QLabel(self.leave)
        self.num1_3.setMinimumSize(QtCore.QSize(60, 25))
        self.num1_3.setMaximumSize(QtCore.QSize(60, 25))
        self.num1_3.setObjectName("num1_3")
        self.horizontalLayout_18.addWidget(self.num1_3)
        self.num_3 = QtWidgets.QLineEdit(self.leave)
        self.num_3.setMinimumSize(QtCore.QSize(200, 25))
        self.num_3.setMaximumSize(QtCore.QSize(200, 25))
        self.num_3.setObjectName("num_3")
        self.horizontalLayout_18.addWidget(self.num_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem13)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.name1_3 = QtWidgets.QLabel(self.leave)
        self.name1_3.setMinimumSize(QtCore.QSize(60, 25))
        self.name1_3.setMaximumSize(QtCore.QSize(60, 25))
        self.name1_3.setObjectName("name1_3")
        self.horizontalLayout_19.addWidget(self.name1_3)
        self.name_3 = QtWidgets.QLineEdit(self.leave)
        self.name_3.setMinimumSize(QtCore.QSize(200, 25))
        self.name_3.setMaximumSize(QtCore.QSize(200, 25))
        self.name_3.setObjectName("name_3")
        self.horizontalLayout_19.addWidget(self.name_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem14)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.other1_3 = QtWidgets.QLabel(self.leave)
        self.other1_3.setMinimumSize(QtCore.QSize(60, 25))
        self.other1_3.setMaximumSize(QtCore.QSize(60, 25))
        self.other1_3.setObjectName("other1_3")
        self.horizontalLayout_21.addWidget(self.other1_3)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.leave)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(200, 25))
        self.dateTimeEdit.setMaximumSize(QtCore.QSize(200, 25))
        self.dateTimeEdit.setProperty("showGroupSeparator", False)
        self.dateTimeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_21.addWidget(self.dateTimeEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem15)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.confire = QtWidgets.QPushButton(self.leave)
        self.confire.setMinimumSize(QtCore.QSize(80, 25))
        self.confire.setMaximumSize(QtCore.QSize(90, 25))
        self.confire.setObjectName("confire")
        self.horizontalLayout_22.addWidget(self.confire)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        spacerItem16 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem16)
        self.xiu_4 = QtWidgets.QLabel(self.leave)
        self.xiu_4.setObjectName("xiu_4")
        self.verticalLayout_6.addWidget(self.xiu_4)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem17)
        self.horizontalLayout_16.addLayout(self.verticalLayout_6)
        self.line_3 = QtWidgets.QFrame(self.leave)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_16.addWidget(self.line_3)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.leave)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(340, 400))
        self.tableWidget_2.setStyleSheet("QTableWidget{background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,0);color: rgba(0, 0, 0,255);border-style:none;border-width:1px;border-radius:0px;alternate-background-color:rgba(0,0,0,32);gridline-color:rgba(0,6,0,0);font:19px \"宋体\";}QHeaderView::section{border-style:none;border-width:1px;border-radius:0px;background-color:rgba(0,0,0,42);border-color:rgba(0,0,0,255);}")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(65)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_16.addWidget(self.tableWidget_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.setting.addTab(self.leave, "")
        self.edituser = QtWidgets.QWidget()
        self.edituser.setObjectName("edituser")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.edituser)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.welcome = QtWidgets.QLabel(self.edituser)
        self.welcome.setMinimumSize(QtCore.QSize(340, 100))
        self.welcome.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:25px \"方正小标宋简体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.welcome.setObjectName("welcome")
        self.verticalLayout_9.addWidget(self.welcome)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_5 = QtWidgets.QLabel(self.edituser)
        self.label_5.setMinimumSize(QtCore.QSize(85, 25))
        self.label_5.setMaximumSize(QtCore.QSize(85, 25))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_17.addWidget(self.label_5)
        self.passold = QtWidgets.QLineEdit(self.edituser)
        self.passold.setMinimumSize(QtCore.QSize(200, 25))
        self.passold.setMaximumSize(QtCore.QSize(200, 25))
        self.passold.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passold.setObjectName("passold")
        self.horizontalLayout_17.addWidget(self.passold)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_6 = QtWidgets.QLabel(self.edituser)
        self.label_6.setMinimumSize(QtCore.QSize(85, 25))
        self.label_6.setMaximumSize(QtCore.QSize(85, 25))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_23.addWidget(self.label_6)
        self.newpass = QtWidgets.QLineEdit(self.edituser)
        self.newpass.setMinimumSize(QtCore.QSize(200, 25))
        self.newpass.setMaximumSize(QtCore.QSize(200, 25))
        self.newpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpass.setObjectName("newpass")
        self.horizontalLayout_23.addWidget(self.newpass)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_7 = QtWidgets.QLabel(self.edituser)
        self.label_7.setMinimumSize(QtCore.QSize(85, 25))
        self.label_7.setMaximumSize(QtCore.QSize(85, 25))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_24.addWidget(self.label_7)
        self.newpass_2 = QtWidgets.QLineEdit(self.edituser)
        self.newpass_2.setMinimumSize(QtCore.QSize(200, 25))
        self.newpass_2.setMaximumSize(QtCore.QSize(200, 25))
        self.newpass_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpass_2.setObjectName("newpass_2")
        self.horizontalLayout_24.addWidget(self.newpass_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.query = QtWidgets.QPushButton(self.edituser)
        self.query.setMinimumSize(QtCore.QSize(80, 30))
        self.query.setMaximumSize(QtCore.QSize(80, 30))
        self.query.setObjectName("query")
        self.horizontalLayout_25.addWidget(self.query)
        self.cancelpass = QtWidgets.QPushButton(self.edituser)
        self.cancelpass.setMinimumSize(QtCore.QSize(80, 30))
        self.cancelpass.setMaximumSize(QtCore.QSize(80, 30))
        self.cancelpass.setObjectName("cancelpass")
        self.horizontalLayout_25.addWidget(self.cancelpass)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.gridLayout_5.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 170, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem18, 1, 0, 1, 1)
        self.setting.addTab(self.edituser, "")
        self.adduser = QtWidgets.QWidget()
        self.adduser.setEnabled(True)
        self.adduser.setObjectName("adduser")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.adduser)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.adduser)
        self.label_12.setMinimumSize(QtCore.QSize(340, 100))
        self.label_12.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:25px \"方正小标宋简体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem19)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.sup_pass_lab = QtWidgets.QLabel(self.adduser)
        self.sup_pass_lab.setMinimumSize(QtCore.QSize(40, 25))
        self.sup_pass_lab.setMaximumSize(QtCore.QSize(80, 25))
        self.sup_pass_lab.setObjectName("sup_pass_lab")
        self.horizontalLayout_27.addWidget(self.sup_pass_lab)
        self.adminpass = QtWidgets.QLineEdit(self.adduser)
        self.adminpass.setMinimumSize(QtCore.QSize(200, 25))
        self.adminpass.setMaximumSize(QtCore.QSize(200, 25))
        self.adminpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.adminpass.setObjectName("adminpass")
        self.horizontalLayout_27.addWidget(self.adminpass)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        spacerItem20 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem20)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.user_lab = QtWidgets.QLabel(self.adduser)
        self.user_lab.setMinimumSize(QtCore.QSize(40, 25))
        self.user_lab.setMaximumSize(QtCore.QSize(80, 25))
        self.user_lab.setObjectName("user_lab")
        self.horizontalLayout_28.addWidget(self.user_lab)
        self.manageuser = QtWidgets.QLineEdit(self.adduser)
        self.manageuser.setMinimumSize(QtCore.QSize(200, 25))
        self.manageuser.setMaximumSize(QtCore.QSize(200, 25))
        self.manageuser.setObjectName("manageuser")
        self.horizontalLayout_28.addWidget(self.manageuser)
        self.verticalLayout_11.addLayout(self.horizontalLayout_28)
        spacerItem21 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem21)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.userpass_lab = QtWidgets.QLabel(self.adduser)
        self.userpass_lab.setMinimumSize(QtCore.QSize(40, 25))
        self.userpass_lab.setMaximumSize(QtCore.QSize(80, 25))
        self.userpass_lab.setObjectName("userpass_lab")
        self.horizontalLayout_29.addWidget(self.userpass_lab)
        self.userpass = QtWidgets.QLineEdit(self.adduser)
        self.userpass.setMinimumSize(QtCore.QSize(200, 25))
        self.userpass.setMaximumSize(QtCore.QSize(200, 25))
        self.userpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.userpass.setObjectName("userpass")
        self.horizontalLayout_29.addWidget(self.userpass)
        self.verticalLayout_11.addLayout(self.horizontalLayout_29)
        spacerItem22 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem22)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.userpass_labagain = QtWidgets.QLabel(self.adduser)
        self.userpass_labagain.setMinimumSize(QtCore.QSize(40, 25))
        self.userpass_labagain.setMaximumSize(QtCore.QSize(80, 25))
        self.userpass_labagain.setObjectName("userpass_labagain")
        self.horizontalLayout_30.addWidget(self.userpass_labagain)
        self.userpass_2 = QtWidgets.QLineEdit(self.adduser)
        self.userpass_2.setMinimumSize(QtCore.QSize(200, 25))
        self.userpass_2.setMaximumSize(QtCore.QSize(200, 25))
        self.userpass_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.userpass_2.setObjectName("userpass_2")
        self.horizontalLayout_30.addWidget(self.userpass_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_30)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        spacerItem23 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem23)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.delmanager_2 = QtWidgets.QPushButton(self.adduser)
        self.delmanager_2.setMinimumSize(QtCore.QSize(80, 25))
        self.delmanager_2.setMaximumSize(QtCore.QSize(80, 25))
        self.delmanager_2.setObjectName("delmanager_2")
        self.horizontalLayout_31.addWidget(self.delmanager_2)
        self.addmanager = QtWidgets.QPushButton(self.adduser)
        self.addmanager.setMinimumSize(QtCore.QSize(80, 25))
        self.addmanager.setMaximumSize(QtCore.QSize(80, 25))
        self.addmanager.setObjectName("addmanager")
        self.horizontalLayout_31.addWidget(self.addmanager)
        self.verticalLayout_10.addLayout(self.horizontalLayout_31)
        self.xiu_5 = QtWidgets.QLabel(self.adduser)
        self.xiu_5.setObjectName("xiu_5")
        self.verticalLayout_10.addWidget(self.xiu_5)
        self.xiu_6 = QtWidgets.QLabel(self.adduser)
        self.xiu_6.setObjectName("xiu_6")
        self.verticalLayout_10.addWidget(self.xiu_6)
        spacerItem24 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem24)
        self.horizontalLayout_26.addLayout(self.verticalLayout_10)
        self.line_4 = QtWidgets.QFrame(self.adduser)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_26.addWidget(self.line_4)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.adduser)
        self.tableWidget_3.setMinimumSize(QtCore.QSize(340, 400))
        self.tableWidget_3.setStyleSheet("QTableWidget{background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,0);color: rgba(0, 0, 0,255);border-style:none;border-width:1px;border-radius:0px;alternate-background-color:rgba(0,0,0,32);gridline-color:rgba(0,6,0,0);font:19px \"宋体\";}QHeaderView::section{border-style:none;border-width:1px;border-radius:0px;background-color:rgba(0,0,0,42);border-color:rgba(0,0,0,255);}")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_26.addWidget(self.tableWidget_3)
        self.gridLayout_6.addLayout(self.horizontalLayout_26, 0, 0, 1, 1)
        self.setting.addTab(self.adduser, "")
        self.gridLayout.addWidget(self.setting, 0, 0, 1, 1)
        # 设置日历为当天时间
        self.dateTimeEdit.setDateTime(QDateTime.currentDateTime())

        self.retranslateUi(userset)
        self.setting.setCurrentIndex(4)
        self.cancelpass.clicked.connect(self.newpass_2.clear)
        self.cancelpass.clicked.connect(self.newpass.clear)
        self.cancelpass.clicked.connect(self.passold.clear)
        self.cancel.clicked.connect(self.other.clear)
        self.cancel.clicked.connect(self.name.clear)
        self.cancel.clicked.connect(self.num.clear)
        QtCore.QMetaObject.connectSlotsByName(userset)

    def retranslateUi(self, userset):
        _translate = QtCore.QCoreApplication.translate
        userset.setWindowTitle(_translate("userset", "设置"))
        self.label_8.setText(_translate("userset", "<html><head/><body><p align=\"center\">常住人员信息录入</p></body></html>"))
        self.inputin.setText(_translate("userset", "本单位人员"))
        self.inputout.setText(_translate("userset", "外单位人员"))
        self.num1.setText(_translate("userset", "编号："))
        self.name1.setText(_translate("userset", "姓名："))
        self.sex1.setText(_translate("userset", "性别："))
        self.sex_man.setText(_translate("userset", "男"))
        self.sex_wo.setText(_translate("userset", "女"))
        self.other1.setText(_translate("userset", "其他："))
        self.cancel.setText(_translate("userset", "清空"))
        self.commit.setText(_translate("userset", "提交"))
        self.start.setText(_translate("userset", "打开相机"))
        self.start_2.setText(_translate("userset", "拍照"))
        self.start_3.setText(_translate("userset", "提交"))
        self.label_2.setText(_translate("userset", "打开相机后开始采集，连续拍摄20张照片，提示采集完成即可。"))
        self.setting.setTabText(self.setting.indexOf(self.insert), _translate("userset", "添加人员"))
        self.label_10.setText(_translate("userset", "<html><head/><body><p align=\"center\">常住人员信息修改</p></body></html>"))
        self.editin.setText(_translate("userset", "本单位人员"))
        self.editout.setText(_translate("userset", "外单位人员"))
        self.num1_2.setText(_translate("userset", "编号："))
        self.name1_2.setText(_translate("userset", "姓名："))
        self.sex1_2.setText(_translate("userset", "<html><head/><body><p>性别：</p></body></html>"))
        self.sex_man_2.setText(_translate("userset", "男"))
        self.sex_wo_2.setText(_translate("userset", "女"))
        self.other1_2.setText(_translate("userset", "其他："))
        self.search.setText(_translate("userset", "查询"))
        self.edit.setText(_translate("userset", "修改"))
        self.delpeo.setText(_translate("userset", "删除"))
        self.xiu.setText(_translate("userset", "1.可对本单位、外单位人员指定编号后进行查询和删除操作。"))
        self.xiu_2.setText(_translate("userset", "2.不可直接修改人员编号，可删除后重新录入。"))
        self.label_3.setText(_translate("userset", "3.可查看本单位或外单位库内所有人员。"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("userset", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("userset", "编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("userset", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("userset", "性别"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("userset", "其他"))
        self.setting.setTabText(self.setting.indexOf(self.update), _translate("userset", "修改人员信息"))
        self.label_11.setText(_translate("userset", "<html><head/><body><p align=\"center\">外出人员管理</p></body></html>"))
        self.num1_3.setText(_translate("userset", "编号："))
        self.name1_3.setText(_translate("userset", "姓名："))
        self.other1_3.setText(_translate("userset", "外出时间："))
        self.dateTimeEdit.setDisplayFormat(_translate("userset", "yyyy/MM/dd HH:mm"))
        self.confire.setText(_translate("userset", "设置外出时间"))
        self.xiu_4.setText(_translate("userset", "    设置对应编号人员外出时间。"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("userset", "1"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("userset", "编号"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("userset", "姓名"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("userset", "性别"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("userset", "外出时间"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("userset", "其他"))
        self.setting.setTabText(self.setting.indexOf(self.leave), _translate("userset", "外出请假"))
        self.welcome.setText(_translate("userset", "<html><head/><body><p align=\"center\">admin，你好！</p></body></html>"))
        self.label_5.setText(_translate("userset", "请输入原密码："))
        self.label_6.setText(_translate("userset", "请输入新密码："))
        self.label_7.setText(_translate("userset", "再次确认密码："))
        self.query.setText(_translate("userset", "确认"))
        self.cancelpass.setText(_translate("userset", "取消"))
        self.setting.setTabText(self.setting.indexOf(self.edituser), _translate("userset", "修改账户密码"))
        self.label_12.setText(_translate("userset", "<html><head/><body><p align=\"center\">账户管理</p></body></html>"))
        self.sup_pass_lab.setText(_translate("userset", "管理员密码："))
        self.user_lab.setText(_translate("userset", "账户名："))
        self.userpass_lab.setText(_translate("userset", "密  码："))
        self.userpass_labagain.setText(_translate("userset", "再次输入密码："))
        self.delmanager_2.setText(_translate("userset", "删除"))
        self.addmanager.setText(_translate("userset", "添加"))
        self.xiu_5.setText(_translate("userset", "1.删除用户输入管理员密码及需删除用户名即可删除。"))
        self.xiu_6.setText(_translate("userset", "2.可查看已创建的所有用户。"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("userset", "1"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("userset", "账户名"))
        self.setting.setTabText(self.setting.indexOf(self.adduser), _translate("userset", "账户编辑"))
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window=QWidget()
    testselfset = Ui_userset()
    testselfset.setupUi(window)
    window.show()  # 最大化显示
    sys.exit(app.exec_())