# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visitor_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import qtawesome

class Ui_visitor(object):
    def setupUi(self, visitor):
        visitor.setObjectName("visitor")
        visitor.resize(720, 566)

        spin_icon = qtawesome.icon('fa5s.user-circle', color='black')
        visitor.setWindowIcon(spin_icon)

        self.gridLayout = QtWidgets.QGridLayout(visitor)
        self.gridLayout.setObjectName("gridLayout")
        self.edit_visitor = QtWidgets.QTabWidget(visitor)
        self.edit_visitor.setEnabled(True)
        self.edit_visitor.setMinimumSize(QtCore.QSize(80, 30))
        self.edit_visitor.setMouseTracking(False)
        self.edit_visitor.setStyleSheet("QWidget::tab{height:40px;width:120px;}")
        self.edit_visitor.setIconSize(QtCore.QSize(16, 16))
        self.edit_visitor.setObjectName("edit_visitor")
        self.insert = QtWidgets.QWidget()
        self.insert.setEnabled(True)
        self.insert.setWhatsThis("")
        self.insert.setObjectName("insert")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.insert)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.insert)
        self.label_8.setMinimumSize(QtCore.QSize(340, 100))
        self.label_8.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:25px \"方正小标宋简体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.num1 = QtWidgets.QLabel(self.insert)
        self.num1.setMinimumSize(QtCore.QSize(80, 25))
        self.num1.setMaximumSize(QtCore.QSize(80, 25))
        self.num1.setObjectName("num1")
        self.horizontalLayout_2.addWidget(self.num1)
        self.num = QtWidgets.QLineEdit(self.insert)
        self.num.setMinimumSize(QtCore.QSize(200, 25))
        self.num.setMaximumSize(QtCore.QSize(200, 25))
        self.num.setObjectName("num")
        self.horizontalLayout_2.addWidget(self.num)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.name1 = QtWidgets.QLabel(self.insert)
        self.name1.setMinimumSize(QtCore.QSize(80, 25))
        self.name1.setMaximumSize(QtCore.QSize(80, 25))
        self.name1.setObjectName("name1")
        self.horizontalLayout_3.addWidget(self.name1)
        self.name = QtWidgets.QLineEdit(self.insert)
        self.name.setMinimumSize(QtCore.QSize(200, 25))
        self.name.setMaximumSize(QtCore.QSize(200, 25))
        self.name.setObjectName("name")
        self.horizontalLayout_3.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sex1 = QtWidgets.QLabel(self.insert)
        self.sex1.setMinimumSize(QtCore.QSize(80, 25))
        self.sex1.setMaximumSize(QtCore.QSize(80, 25))
        self.sex1.setObjectName("sex1")
        self.horizontalLayout_4.addWidget(self.sex1)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.groupBox_2 = QtWidgets.QGroupBox(self.insert)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 25))
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 25))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.sex_man = QtWidgets.QRadioButton(self.groupBox_2)
        self.sex_man.setGeometry(QtCore.QRect(32, 4, 100, 18))
        self.sex_man.setMinimumSize(QtCore.QSize(100, 0))
        self.sex_man.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sex_man.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.sex_man.setChecked(True)
        self.sex_man.setObjectName("sex_man")
        self.sex_wo = QtWidgets.QRadioButton(self.groupBox_2)
        self.sex_wo.setGeometry(QtCore.QRect(122, 4, 100, 18))
        self.sex_wo.setMinimumSize(QtCore.QSize(100, 0))
        self.sex_wo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sex_wo.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.sex_wo.setObjectName("sex_wo")
        self.horizontalLayout_32.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_32)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.date_time = QtWidgets.QLabel(self.insert)
        self.date_time.setMinimumSize(QtCore.QSize(80, 25))
        self.date_time.setMaximumSize(QtCore.QSize(80, 25))
        self.date_time.setObjectName("date_time")
        self.horizontalLayout_17.addWidget(self.date_time)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.insert)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(200, 25))
        self.dateTimeEdit.setMaximumSize(QtCore.QSize(200, 25))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_17.addWidget(self.dateTimeEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.other1 = QtWidgets.QLabel(self.insert)
        self.other1.setMinimumSize(QtCore.QSize(80, 25))
        self.other1.setMaximumSize(QtCore.QSize(80, 25))
        self.other1.setObjectName("other1")
        self.horizontalLayout_5.addWidget(self.other1)
        self.other = QtWidgets.QLineEdit(self.insert)
        self.other.setMinimumSize(QtCore.QSize(200, 25))
        self.other.setMaximumSize(QtCore.QSize(200, 25))
        self.other.setObjectName("other")
        self.horizontalLayout_5.addWidget(self.other)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cancel = QtWidgets.QPushButton(self.insert)
        self.cancel.setMinimumSize(QtCore.QSize(80, 25))
        self.cancel.setMaximumSize(QtCore.QSize(80, 25))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_6.addWidget(self.cancel)
        self.commit = QtWidgets.QPushButton(self.insert)
        self.commit.setMinimumSize(QtCore.QSize(80, 25))
        self.commit.setMaximumSize(QtCore.QSize(80, 25))
        self.commit.setObjectName("commit")
        self.horizontalLayout_6.addWidget(self.commit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.insert)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.insert)
        self.label.setMinimumSize(QtCore.QSize(330, 400))
        self.label.setStyleSheet("background-color:rgba(0,0,0,91);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.start = QtWidgets.QPushButton(self.insert)
        self.start.setMinimumSize(QtCore.QSize(80, 25))
        self.start.setMaximumSize(QtCore.QSize(80, 25))
        self.start.setObjectName("start")
        self.horizontalLayout_7.addWidget(self.start)
        self.start_2 = QtWidgets.QPushButton(self.insert)
        self.start_2.setMinimumSize(QtCore.QSize(80, 25))
        self.start_2.setMaximumSize(QtCore.QSize(80, 25))
        self.start_2.setObjectName("start_2")
        self.horizontalLayout_7.addWidget(self.start_2)
        self.start_3 = QtWidgets.QPushButton(self.insert)
        self.start_3.setMinimumSize(QtCore.QSize(80, 25))
        self.start_3.setMaximumSize(QtCore.QSize(80, 25))
        self.start_3.setObjectName("start_3")
        self.horizontalLayout_7.addWidget(self.start_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.label_2 = QtWidgets.QLabel(self.insert)
        self.label_2.setMinimumSize(QtCore.QSize(300, 25))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.edit_visitor.addTab(self.insert, "")
        self.update = QtWidgets.QWidget()
        self.update.setObjectName("update")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.update)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.update)
        self.label_10.setMinimumSize(QtCore.QSize(250, 100))
        self.label_10.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:25px \"方正小标宋简体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.verticalLayout_4.addLayout(self.horizontalLayout_65)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.num1_2 = QtWidgets.QLabel(self.update)
        self.num1_2.setMinimumSize(QtCore.QSize(80, 25))
        self.num1_2.setMaximumSize(QtCore.QSize(80, 25))
        self.num1_2.setObjectName("num1_2")
        self.horizontalLayout_10.addWidget(self.num1_2)
        self.num_2 = QtWidgets.QLineEdit(self.update)
        self.num_2.setMinimumSize(QtCore.QSize(200, 25))
        self.num_2.setMaximumSize(QtCore.QSize(200, 25))
        self.num_2.setObjectName("num_2")
        self.horizontalLayout_10.addWidget(self.num_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.name1_2 = QtWidgets.QLabel(self.update)
        self.name1_2.setMinimumSize(QtCore.QSize(80, 25))
        self.name1_2.setMaximumSize(QtCore.QSize(80, 25))
        self.name1_2.setObjectName("name1_2")
        self.horizontalLayout_11.addWidget(self.name1_2)
        self.name_2 = QtWidgets.QLineEdit(self.update)
        self.name_2.setMinimumSize(QtCore.QSize(200, 25))
        self.name_2.setMaximumSize(QtCore.QSize(200, 25))
        self.name_2.setObjectName("name_2")
        self.horizontalLayout_11.addWidget(self.name_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sex1_2 = QtWidgets.QLabel(self.update)
        self.sex1_2.setMinimumSize(QtCore.QSize(80, 25))
        self.sex1_2.setMaximumSize(QtCore.QSize(80, 25))
        self.sex1_2.setMouseTracking(True)
        self.sex1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sex1_2.setLineWidth(1)
        self.sex1_2.setObjectName("sex1_2")
        self.horizontalLayout_12.addWidget(self.sex1_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.update)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 25))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 25))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.sex_man_2 = QtWidgets.QRadioButton(self.groupBox)
        self.sex_man_2.setGeometry(QtCore.QRect(31, 2, 100, 18))
        self.sex_man_2.setMinimumSize(QtCore.QSize(100, 0))
        self.sex_man_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sex_man_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sex_man_2.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.sex_man_2.setChecked(True)
        self.sex_man_2.setAutoExclusive(True)
        self.sex_man_2.setObjectName("sex_man_2")
        self.sex_wo_2 = QtWidgets.QRadioButton(self.groupBox)
        self.sex_wo_2.setGeometry(QtCore.QRect(120, 2, 100, 18))
        self.sex_wo_2.setMinimumSize(QtCore.QSize(100, 0))
        self.sex_wo_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sex_wo_2.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.sex_wo_2.setObjectName("sex_wo_2")
        self.horizontalLayout_9.addWidget(self.groupBox)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.date_time_2 = QtWidgets.QLabel(self.update)
        self.date_time_2.setMinimumSize(QtCore.QSize(80, 25))
        self.date_time_2.setMaximumSize(QtCore.QSize(80, 25))
        self.date_time_2.setObjectName("date_time_2")
        self.horizontalLayout_18.addWidget(self.date_time_2)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.update)
        self.dateTimeEdit_2.setMinimumSize(QtCore.QSize(200, 25))
        self.dateTimeEdit_2.setMaximumSize(QtCore.QSize(200, 25))
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.horizontalLayout_18.addWidget(self.dateTimeEdit_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.other1_2 = QtWidgets.QLabel(self.update)
        self.other1_2.setMinimumSize(QtCore.QSize(80, 25))
        self.other1_2.setMaximumSize(QtCore.QSize(80, 25))
        self.other1_2.setObjectName("other1_2")
        self.horizontalLayout_13.addWidget(self.other1_2)
        self.other_2 = QtWidgets.QLineEdit(self.update)
        self.other_2.setMinimumSize(QtCore.QSize(200, 25))
        self.other_2.setMaximumSize(QtCore.QSize(200, 25))
        self.other_2.setObjectName("other_2")
        self.horizontalLayout_13.addWidget(self.other_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.search = QtWidgets.QPushButton(self.update)
        self.search.setMinimumSize(QtCore.QSize(80, 25))
        self.search.setMaximumSize(QtCore.QSize(80, 25))
        self.search.setObjectName("search")
        self.horizontalLayout_14.addWidget(self.search)
        self.edit = QtWidgets.QPushButton(self.update)
        self.edit.setMinimumSize(QtCore.QSize(80, 25))
        self.edit.setMaximumSize(QtCore.QSize(80, 25))
        self.edit.setObjectName("edit")
        self.horizontalLayout_14.addWidget(self.edit)
        self.delpeo = QtWidgets.QPushButton(self.update)
        self.delpeo.setMinimumSize(QtCore.QSize(80, 25))
        self.delpeo.setMaximumSize(QtCore.QSize(80, 25))
        self.delpeo.setObjectName("delpeo")
        self.horizontalLayout_14.addWidget(self.delpeo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.xiu = QtWidgets.QLabel(self.update)
        self.xiu.setObjectName("xiu")
        self.verticalLayout_4.addWidget(self.xiu)
        self.xiu_2 = QtWidgets.QLabel(self.update)
        self.xiu_2.setObjectName("xiu_2")
        self.verticalLayout_4.addWidget(self.xiu_2)
        spacerItem13 = QtWidgets.QSpacerItem(321, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.update)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_15.addWidget(self.line_2)
        self.tableWidget = QtWidgets.QTableWidget(self.update)
        self.tableWidget.setMinimumSize(QtCore.QSize(340, 400))
        self.tableWidget.setStyleSheet("QTableWidget{background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,0);color: rgba(0, 0, 0,255);border-style:none;border-width:1px;border-radius:0px;alternate-background-color:rgba(0,0,0,36);gridline-color:rgba(0,6,3,0);font:19px \"宋体\";}QHeaderView::section{border-style:none;border-width:1px;border-radius:0px;background-color:rgba(0,0,0,42);border-color:rgba(0,0,0,136);}")
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.horizontalLayout_15.addWidget(self.tableWidget)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.edit_visitor.addTab(self.update, "")
        self.gridLayout.addWidget(self.edit_visitor, 0, 0, 1, 1)

        self.retranslateUi(visitor)
        self.edit_visitor.setCurrentIndex(1)
        self.cancel.clicked.connect(self.other.clear)
        self.cancel.clicked.connect(self.name.clear)
        self.cancel.clicked.connect(self.num.clear)
        QtCore.QMetaObject.connectSlotsByName(visitor)

    def retranslateUi(self, visitor):
        _translate = QtCore.QCoreApplication.translate
        visitor.setWindowTitle(_translate("visitor", "来访系统"))
        self.label_8.setText(_translate("visitor", "<html><head/><body><p align=\"center\">来访人员信息录入</p></body></html>"))
        self.num1.setText(_translate("visitor", "编号："))
        self.name1.setText(_translate("visitor", "姓名："))
        self.sex1.setText(_translate("visitor", "性别："))
        self.sex_man.setText(_translate("visitor", "男"))
        self.sex_wo.setText(_translate("visitor", "女"))
        self.date_time.setText(_translate("visitor", "来访截止时间："))
        self.other1.setText(_translate("visitor", "其他："))
        self.cancel.setText(_translate("visitor", "清空"))
        self.commit.setText(_translate("visitor", "提交"))
        self.start.setText(_translate("visitor", "打开相机"))
        self.start_2.setText(_translate("visitor", "拍照"))
        self.start_3.setText(_translate("visitor", "提交"))
        self.label_2.setText(_translate("visitor", "打开相机后开始采集，连续拍摄20张照片，提示采集完成即可。"))
        self.edit_visitor.setTabText(self.edit_visitor.indexOf(self.insert), _translate("visitor", "添加人员"))
        self.label_10.setText(_translate("visitor", "<html><head/><body><p align=\"center\">来访人员信息修改</p></body></html>"))
        self.num1_2.setText(_translate("visitor", "编号："))
        self.name1_2.setText(_translate("visitor", "姓名："))
        self.sex1_2.setText(_translate("visitor", "<html><head/><body><p>性别：</p></body></html>"))
        self.sex_man_2.setText(_translate("visitor", "男"))
        self.sex_wo_2.setText(_translate("visitor", "女"))
        self.date_time_2.setText(_translate("visitor", "来访截止时间："))
        self.other1_2.setText(_translate("visitor", "其他："))
        self.search.setText(_translate("visitor", "查询"))
        self.edit.setText(_translate("visitor", "修改"))
        self.delpeo.setText(_translate("visitor", "删除"))
        self.xiu.setText(_translate("visitor", "1.可指定编号后进行查询和删除操作。"))
        self.xiu_2.setText(_translate("visitor", "2.不可直接修改人员编号，可删除后重新录入。"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("visitor", "编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("visitor", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("visitor", "性别"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("visitor", "日期时间"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("visitor", "其他"))
        self.edit_visitor.setTabText(self.edit_visitor.indexOf(self.update), _translate("visitor", "修改人员信息"))
