# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import qtawesome

class Ui_inquire(object):
    def setupUi(self, inquire):
        inquire.setObjectName("inquire")
        inquire.resize(711, 565)

        spin_icon = qtawesome.icon('fa5s.search', color='black')
        inquire.setWindowIcon(spin_icon)

        self.gridLayout = QtWidgets.QGridLayout(inquire)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(inquire)
        self.label.setMinimumSize(QtCore.QSize(90, 20))
        self.label.setMaximumSize(QtCore.QSize(130, 20))
        self.label.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,255);border-style:none;border-width:1px;border-radius:0px;font:19px \"宋体\";font-style:normal;font-weight: normal;text-decoration:blink;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.starting_time = QtWidgets.QDateTimeEdit(inquire)
        self.starting_time.setMinimumSize(QtCore.QSize(200, 25))
        self.starting_time.setMaximumSize(QtCore.QSize(250, 25))
        self.starting_time.setCalendarPopup(True)
        self.starting_time.setObjectName("starting_time")
        self.horizontalLayout.addWidget(self.starting_time)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(inquire)
        self.label_2.setMinimumSize(QtCore.QSize(90, 20))
        self.label_2.setMaximumSize(QtCore.QSize(130, 20))
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,255);border-style:none;border-width:1px;border-radius:0px;font:19px \"宋体\";font-style:normal;font-weight: normal;text-decoration:blink;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.end_time = QtWidgets.QDateTimeEdit(inquire)
        self.end_time.setMinimumSize(QtCore.QSize(200, 25))
        self.end_time.setMaximumSize(QtCore.QSize(250, 25))
        self.end_time.setCalendarPopup(True)
        self.end_time.setObjectName("end_time")
        self.horizontalLayout_2.addWidget(self.end_time)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(inquire)
        self.groupBox.setMinimumSize(QtCore.QSize(310, 30))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox.setStyleSheet("#groupBox{border:none}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.checkin = QtWidgets.QRadioButton(self.groupBox)
        self.checkin.setGeometry(QtCore.QRect(10, 10, 89, 16))
        self.checkin.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.checkin.setChecked(True)
        self.checkin.setObjectName("checkin")
        self.comein = QtWidgets.QRadioButton(self.groupBox)
        self.comein.setGeometry(QtCore.QRect(120, 10, 89, 16))
        self.comein.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.comein.setObjectName("comein")
        self.goout = QtWidgets.QRadioButton(self.groupBox)
        self.goout.setGeometry(QtCore.QRect(240, 10, 89, 16))
        self.goout.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,254);border-style:none;border-width:0px;border-radius:8px;font:18px \"宋体\";font-style:normal;font-weight: lighter;text-decoration:blink;")
        self.goout.setObjectName("goout")
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(inquire)
        self.label_3.setMinimumSize(QtCore.QSize(70, 20))
        self.label_3.setMaximumSize(QtCore.QSize(150, 20))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,255);color: rgba(0, 0, 0,255);border-style:none;border-width:1px;border-radius:0px;font:19px \"宋体\";font-style:normal;font-weight: normal;text-decoration:blink;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(inquire)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(650, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.search = QtWidgets.QPushButton(inquire)
        self.search.setMinimumSize(QtCore.QSize(80, 25))
        self.search.setMaximumSize(QtCore.QSize(80, 25))
        self.search.setObjectName("search")
        self.horizontalLayout_3.addWidget(self.search)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtWidgets.QTableWidget(inquire)
        self.tableWidget.setStyleSheet("QTableWidget{background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,0);color: rgba(0, 0, 0,255);border-style:none;border-width:1px;border-radius:0px;alternate-background-color:rgba(0,0,0,36);gridline-color:rgba(0,6,3,0);font:19px \"宋体\";}QHeaderView::section{border-style:none;border-width:1px;border-radius:0px;background-color:rgba(0,0,0,42);border-color:rgba(0,0,0,136);}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(inquire)
        QtCore.QMetaObject.connectSlotsByName(inquire)

    def retranslateUi(self, inquire):
        _translate = QtCore.QCoreApplication.translate
        inquire.setWindowTitle(_translate("inquire", "查询系统"))
        self.label.setText(_translate("inquire", "<html><head/><body><p align=\"center\">起始时间：</p></body></html>"))
        self.starting_time.setDisplayFormat(_translate("inquire", "yyyy/MM/dd HH:mm:ss"))
        self.label_2.setText(_translate("inquire", "<html><head/><body><p align=\"center\">截止时间：</p></body></html>"))
        self.end_time.setDisplayFormat(_translate("inquire", "yyyy/MM/dd HH:mm:ss"))
        self.checkin.setText(_translate("inquire", "考勤记录"))
        self.comein.setText(_translate("inquire", "门禁记录"))
        self.goout.setText(_translate("inquire", "外出记录"))
        self.label_3.setText(_translate("inquire", "<html><head/><body><p align=\"center\">关键词：</p></body></html>"))
        self.search.setText(_translate("inquire", "查询"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("inquire", "编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("inquire", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("inquire", "日期时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("inquire", "其他"))
