# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets
import qtawesome

class Ui_checkin(object):
    def setupUi(self, checkin):
        checkin.setObjectName("checkin")
        checkin.resize(780, 566)
        checkin.setMinimumSize(QtCore.QSize(720, 566))

        spin_icon = qtawesome.icon('fa5s.user-edit', color='black')
        checkin.setWindowIcon(spin_icon)

        self.gridLayout = QtWidgets.QGridLayout(checkin)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(checkin)
        self.label.setMinimumSize(QtCore.QSize(483, 500))
        self.label.setStyleSheet("background-color:rgba(0,0,0,91);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(checkin)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(checkin)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(60, 25))
        self.dateTimeEdit.setMaximumSize(QtCore.QSize(60, 25))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout.addWidget(self.dateTimeEdit)
        self.start = QtWidgets.QPushButton(checkin)
        self.start.setMinimumSize(QtCore.QSize(80, 25))
        self.start.setMaximumSize(QtCore.QSize(80, 25))
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.display = QtWidgets.QLineEdit(checkin)
        self.display.setMinimumSize(QtCore.QSize(0, 25))
        self.display.setObjectName("display")
        self.horizontalLayout.addWidget(self.display)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(checkin)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.display_table = QtWidgets.QTableWidget(checkin)
        self.display_table.setMinimumSize(QtCore.QSize(200, 0))
        self.display_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.display_table.setStyleSheet("QTableWidget{background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,0);color: rgba(0, 0, 0,255);border-style:none;border-width:1px;border-radius:0px;alternate-background-color:rgba(0,0,0,32);gridline-color:rgba(0,6,0,0);font:19px \"宋体\";}QHeaderView::section{border-style:none;border-width:1px;border-radius:0px;background-color:rgba(0,0,0,42);border-color:rgba(0,0,0,255);}")
        self.display_table.setObjectName("display_table")
        self.display_table.setColumnCount(4)
        self.display_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.display_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_table.setHorizontalHeaderItem(3, item)
        self.display_table.horizontalHeader().setDefaultSectionSize(80)
        self.display_table.horizontalHeader().setMinimumSectionSize(40)
        self.display_table.horizontalHeader().setSortIndicatorShown(True)
        self.display_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.display_table)
        self.belate_table = QtWidgets.QTableWidget(checkin)
        self.belate_table.setMaximumSize(QtCore.QSize(16777215, 200))
        self.belate_table.setStyleSheet("QTableWidget{background-color:rgba(0,0,0,0);border-color:rgba(0,0,0,0);color: rgba(0, 0, 0,255);border-style:none;border-width:1px;border-radius:0px;alternate-background-color:rgba(0,0,0,32);gridline-color:rgba(0,6,0,0);font:19px \"宋体\";}QHeaderView::section{border-style:none;border-width:1px;border-radius:0px;background-color:rgba(0,0,0,42);border-color:rgba(0,0,0,255);}")
        self.belate_table.setObjectName("belate_table")
        self.belate_table.setColumnCount(4)
        self.belate_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.belate_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.belate_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.belate_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.belate_table.setHorizontalHeaderItem(3, item)
        self.belate_table.horizontalHeader().setDefaultSectionSize(80)
        self.belate_table.horizontalHeader().setMinimumSectionSize(40)
        self.belate_table.horizontalHeader().setSortIndicatorShown(True)
        self.belate_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.belate_table)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(checkin)
        QtCore.QMetaObject.connectSlotsByName(checkin)

    def retranslateUi(self, checkin):
        _translate = QtCore.QCoreApplication.translate
        checkin.setWindowTitle(_translate("checkin", "考勤系统"))
        self.label_2.setText(_translate("checkin", "设置考勤结束时间："))
        self.dateTimeEdit.setDisplayFormat(_translate("checkin", "HH:mm"))
        self.start.setText(_translate("checkin", "开始考勤"))
        self.display_table.setSortingEnabled(True)
        item = self.display_table.horizontalHeaderItem(0)
        item.setText(_translate("checkin", "编号"))
        item = self.display_table.horizontalHeaderItem(1)
        item.setText(_translate("checkin", "姓名"))
        item = self.display_table.horizontalHeaderItem(2)
        item.setText(_translate("checkin", "验证时间"))
        item = self.display_table.horizontalHeaderItem(3)
        item.setText(_translate("checkin", "考勤情况"))
        item = self.belate_table.horizontalHeaderItem(0)
        item.setText(_translate("checkin", "编号"))
        item = self.belate_table.horizontalHeaderItem(1)
        item.setText(_translate("checkin", "姓名"))
        item = self.belate_table.horizontalHeaderItem(2)
        item.setText(_translate("checkin", "人员情况"))
        item = self.belate_table.horizontalHeaderItem(3)
        item.setText(_translate("checkin", "考勤情况"))
